// This file is autogenerated by scripts/generate_node_factory_map.py. Do not edit manually, but edit the respective scripts to reflect the needed changes!
#include "generated/maps/NodeFactoryMap.hpp"
